# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_adminusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUsers',
            new_name='AdminUser',
        ),
    ]
