# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_delete_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
