# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0010_remove_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
