# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0011_question_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
