# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0012_auto_20170917_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
